#   /$$$$$$  /$$                               /$$   /$$     /$$
#  /$$__  $$| $$                              |__/  | $$    | $$
# | $$  \ $$| $$  /$$$$$$   /$$$$$$$  /$$$$$$  /$$ /$$$$$$ /$$$$$$   /$$   /$$
# | $$$$$$$$| $$ |____  $$ /$$_____/ /$$__  $$| $$|_  $$_/|_  $$_/  | $$  | $$
# | $$__  $$| $$  /$$$$$$$| $$      | $$  \__/| $$  | $$    | $$    | $$  | $$
# | $$  | $$| $$ /$$__  $$| $$      | $$      | $$  | $$ /$$| $$ /$$| $$  | $$
# | $$  | $$| $$|  $$$$$$$|  $$$$$$$| $$      | $$  |  $$$$/|  $$$$/|  $$$$$$$
# |__/  |__/|__/ \_______/ \_______/|__/      |__/   \___/   \___/   \____  $$
#                                                                    /$$  | $$
#                                                                   |  $$$$$$/
#                                                                    \______/

import = [
  # "~/.config/alacritty/catpuccin/catppuccin-mocha.toml",
  "~/.config/alacritty/rose-pine/rose-pine.toml",
  "~/.config/alacritty/fonts.toml",
]
live_config_reload = true

[env]
TERM = "xterm-256color"
WINIT_X11_SCALE_FACTOR = "1.0"

[window]
decorations = "full"
startup_mode = "Windowed"
dynamic_title = true

[window.dimensions]
columns = 82
lines = 25

[window.padding]
x = 5
y = 5

[cursor]
unfocused_hollow = false

[cursor.style]
shape = "Block"
blinking = "On"
